# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20171026_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='presentation',
        ),
        migrations.AddField(
            model_name='presentation',
            name='pres_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pres_part', to='plan.Participant'),
        ),
    ]
