# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20171029_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Учитель'), ('Профессор', 'Профессор')], default='Студент', max_length=9),
        ),
    ]
