# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20171029_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('ST', 'Студент'), ('TE', 'Преподаватель'), ('PR', 'Профессор')], default='ST', max_length=9),
        ),
    ]
