# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20171030_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Group'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Group'),
        ),
    ]
